publish_to: none
name: minigpu_web
description: A web library for minigpu wasm.
version: 1.0.0
repository: https://github.com/MichealReed/minigpu/tree/master/minigpu_web

#####

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  js: ^0.6.3
  js_interop_utils: ^1.0.5
  minigpu_platform_interface:
    path: ../minigpu_platform_interface

dev_dependencies:
  flutter_lints: ^3.0.1

#####

flutter:
  plugin:
    implements: minigpu
    platforms:
      web:
        pluginClass: MinigpuWeb
        fileName: minigpu_web.dart

  assets:
    - packages/minigpu_web/build/minigpu_web.loader.js
    - packages/minigpu_web/build/minigpu_web.wasm
    - packages/minigpu_web/build/minigpu_web.js