
name: minigpu_web
description: A web library for minigpu wasm. A library to brings multiplatform GPU compute to Dart and Flutter using GPU.cpp and Google Dawn.
version: 1.1.2
repository: https://github.com/PracticalXR/minigpu

#####

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  js: ^0.6.3
  js_interop_utils: ^1.0.5
  minigpu_platform_interface: ^1.1.2
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1

#####

flutter:
  plugin:
    implements: minigpu
    platforms:
      web:
        pluginClass: MinigpuWeb
        fileName: minigpu_web.dart

  assets:
    - packages/minigpu_web/web/minigpu_web.loader.js
    - packages/minigpu_web/web/minigpu_web.wasm
    - packages/minigpu_web/web/minigpu_web.js