name: example
description: Demonstrates how to use the minigpu package.
version: 1.0.0
publish_to: none

#####

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  minigpu:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

#####

flutter:
  uses-material-design: true

  assets:
    - assets/hello.shader
