publish_to: none
name: minigpu
description: A gpu compute library for dart.
version: 1.0.0
repository: https://github.com/MichealReed/minigpu/tree/master/minigpu

#####

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  minigpu_platform_interface:
    path: ../minigpu_platform_interface
  minigpu_ffi:
    path: ../minigpu_ffi
  minigpu_web:
    path: ../minigpu_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  test: ^1.25.15

#####

flutter:
  plugin:
    platforms:
      web:
        default_package: minigpu_web
  assets:
    - assets/hello.shader
    