
name: minigpu
description: A library that brings multiplatform GPU compute to Dart and Flutter by wrapping the gpu.cpp library and webgpu with a Dawn backend.
version: 1.1.2
repository: https://github.com/PracticalXR/minigpu

#####

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  minigpu_platform_interface: ^1.1.2
  minigpu_ffi: ^1.1.2
  minigpu_web: ^1.1.2

dev_dependencies:
  test: ^1.25.15

#####

platforms:
  windows:
  android:
  linux:
  ios:
  macos:
  web:
