publish_to: none
name: minigpu
description: A library that brings multiplatform GPU compute to Dart and Flutter by wrapping the gpu.cpp library and webgpu with a Dawn backend.
version: 1.0.2
repository: https://github.com/PracticalXR/minigpu

#####

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  minigpu_platform_interface:
    path: ../minigpu_platform_interface
  minigpu_ffi:
    path: ../minigpu_ffi
  minigpu_web:
    path: ../minigpu_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  test: ^1.25.15

#####

platforms:
  windows:
  android:
  linux:
  ios:
  macos:

flutter:
  plugin:
    platforms:
      web:
        default_package: minigpu_web
  assets:
    - assets/hello.shader
