publish_to: none
name: minigpu_platform_interface
description: A web library for minigpu wasm.
version: 1.0.0
repository: https://github.com/MichealReed/minigpu/tree/master/minigpu_platform_interface

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
