publish_to: none
name: minigpu_ffi
description: FFI implementation of minigpu. A library to brings multiplatform GPU compute to Dart and Flutter using GPU.cpp and Google Dawn.
version: 1.0.3
repository: https://github.com/PracticalXR/minigpu

#####

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  ffi: ^2.0.2
  minigpu_platform_interface:
    path: ../minigpu_platform_interface
  native_toolchain_cmake: ^0.0.4

dev_dependencies:
  flutter_lints: ^2.0.1
  ffigen: ^18.0.0

#####

ffigen:
  name: minigpuFfiBindings
  description: Bindings for minigpu.h
  output: "lib/minigpu_ffi_bindings.dart"
  headers:
    entry-points:
      - "src/include/minigpu.h"
    include-directives:
      - "src/include/*.h"
      - "/usr/lib/clang/18/include/stdbool.h"
  preamble: |
    // ignore_for_file: camel_case_types
    // ignore_for_file: prefer_double_quotes
    // ignore_for_file: non_constant_identifier_names
    // ignore_for_file: constant_identifier_names
    // ignore_for_file: prefer_expression_function_bodies
    // ignore_for_file: sort_constructors_first
    // ignore_for_file: unused_element 
  llvm-path:
    - /usr/lib64/libclang.so
  compiler-opts:
    - -I/usr/lib/clang/18/include/
  ffi-native:

